<?php

/* 
Revision history:

Date        Who     What
----        ---     ----
16-Sep-03   NL      Creation.
              
*/

    ob_start(); // avoid indavertantly sending output (before HTTP Headers sent) 

include_once ( 'htmlhead.php'        );
include_once ( 'htmlfoot.php'        );  

    function newlines($n)
    {
        for ($i = 0; $i < $n; $i++)
        {
            echo "<br>\n";
        }
    }

    function display_content()
    { 
    
        /*  The following HTML was generated by OpenOffice from the Word doc
            with the following changes:
            1.  Remove all references to below, shown below, seen below, and see below.
            2.  Remove all images; For form buttons, replace with text.
            3.  Nest lists as necessary.
            4.  Remove hyperlinks.
        */    
        
        $msg = <<< HERE

<H3 CLASS="western">Review e-mail status 
</H3>
<P CLASS="western">The distribution and installation of the ASI
client via e-mail is an iterative process. For this reason, you need
an easy way to review the status of the process, and take the action
necessary to ensure its successful completion, to the greatest
possible extent.</P>
<P CLASS="western" STYLE="page-break-inside: avoid">The <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Email
Status for &lt;Site Name&gt;</FONT></FONT></FONT> page
lets you review the status of the ASI client e-mail distribution and
installation process at a glance and:</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western">Clear confirmations for one,
	some, or all recipients whose e-mail address you entered on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
	Email Addresses for &lt;Site Name&gt;</FONT></FONT></FONT> page,</P>
	<LI><P CLASS="ww-list-bullet1-western">Delete one, some, or all
	e-mail addresses you entered in the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
	Email Addresses for &lt;Site Name&gt;</FONT></FONT></FONT> page, and</P>
	<LI><P CLASS="ww-list-bullet1-western">Send the ASI client
	distribution and installation message to one, some or all recipients
	whose e-mail address you entered on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
	Email Addresses for &lt;Site Name&gt;</FONT></FONT></FONT> page.</P>
</UL>
<P CLASS="western" STYLE="page-break-inside: avoid">In the upper part
of the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Email
Status for &lt;Site Name&gt;</FONT></FONT></FONT> page, you will find
a control panel that lets you:</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Clear
	Response Confirmations</FONT></B>. Clicking the 
	<FONT FACE="Verdana, sans-serif"><B>Clear Confirmations</B></FONT>
	button will reset the <B><FONT FACE="Verdana, sans-serif">Response
	Confirmation</FONT></B> value to <FONT FACE="Courier New, monospace">no</FONT>
	for all e-mail addresses, letting you re-send the ASI client
	distribution and installation e-mail message to all destinations.</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Delete
	Addresses</FONT></B>. This powerful action should be used with care.
	It lets you:</P>
    <UL>
    	<LI><P CLASS="ww-list-bullet-21-western">Delete all addresses from
    	which you have received confirmation that the installation of the
    	ASI client has been completed successfully, clicking on the radio
    	button to the right of the <FONT FACE="Verdana, sans-serif">Delete
    	only those with confirmed installation</FONT> label, and clicking on
    	the <FONT FACE="Verdana, sans-serif"><B>Delete Addresses</B></FONT> button.</P>
    	<LI><P CLASS="ww-list-bullet-21-western">Delete
    	all addresses regardless of whether you have received confirmation
    	of a successfully completed installation clicking on the radio
    	button to the right of the <FONT FACE="Verdana, sans-serif">Delete
    	all addresses</FONT> label, and clicking on the 
    	<FONT FACE="Verdana, sans-serif"><B>Delete Addresses</B></FONT>
    	button.</P>
    </UL>
</UL>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Send
	Email</FONT></B>. The <B><FONT FACE="Verdana, sans-serif">Send Email</FONT></B>
	action lets you 
	</P>
    <UL>
    	<LI><P CLASS="ww-list-bullet-21-western">Send ASI client
    	distribution and installation e-mail messages to all recipients from
    	whom you have not received confirmation, by clicking on the <FONT FACE="Verdana, sans-serif">Resend
    	emails to addresses without confirmed responses</FONT> check box,
    	and clicking on the 
    	<FONT FACE="Verdana, sans-serif"><B>Send Email</B></FONT>
    	button.</P>
    	<LI><P CLASS="ww-list-bullet-21-western">Send
    	all ASI client distribution and installation e-mail messages not yet
    	sent by clicking on the <FONT FACE="Verdana, sans-serif">Send all
    	pending (unsent) email</FONT> check box, and clicking on the 
    	<FONT FACE="Verdana, sans-serif"><B>Send Email</B></FONT>
    	button.</P>
    </UL>
</UL>
<P CLASS="western">In the lower portion of the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Email
Status for &lt;Site Name&gt;</FONT></FONT></FONT> page, you will find
a table listing all the e-mail addresses you entered on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
Email Addresses for &lt;Site Name&gt;</FONT></FONT></FONT> page. Each
entry in the table consists of:</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Email
	Address.</FONT></B> The e-mail address of a recipient of the ASI
	client distribution and installation e-mail message</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Email
	Sent.</FONT></B> Has the ASI client e-mail distribution and
	installation e-mail message been sent to this recipient?</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Response
	Confirmation.</FONT></B> Has the recipient of ASI client e-mail
	distribution and installation e-mail message responded to the
	message?</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Installation
	Confirmation.</FONT></B> Has the installation of ASI client e-mail
	been completed successfully?</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Action.</FONT></B>
	For each entry in the table, you can take one of the following
	actions: 
	</P>
    <UL>
    	<LI><P CLASS="ww-list-bullet-21-western">Delete an e-mail address by
    	clicking on the <FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">[delete]</FONT></U></FONT>
    	link in the <B>Action</B> column of an e-mail address entry 
    	</P>
    	<LI><P CLASS="ww-list-bullet-21-western">Clear the response
    	confirmations for an e-mail address by clicking on the
    	<FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">[clear
    	response confirmation]</FONT></U></FONT> link in the <B>Action</B>
    	column of an e-mail address entry. This is useful if you want to
    	re-send the ASI client distribution and installation e-mail message
    	to individual recipients, fro example those who received the message
    	but did not take the requested action.</P>
    	<LI><P CLASS="ww-list-bullet-21-western">Send the ASI client
    	distribution and installation e-mail message to individual
    	recipients, regardless of the confirmation status for their
    	locations clicking on the <FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">[send
    	email to this address]</FONT></U></FONT><FONT FACE="Verdana, sans-serif">
    	</FONT>link in the <B><FONT FACE="Verdana, sans-serif">Action</FONT></B>
    	column of an e-mail address entry</P>
    </UL>
</UL>
<P CLASS="western">Whenever you take a <FONT FACE="Verdana, sans-serif">clear
confirmations</FONT>, <FONT FACE="Verdana, sans-serif">delete</FONT>,
or <FONT FACE="Verdana, sans-serif">send e-mail </FONT>action,
whether applied to an individual address or all addresses, you will
be required to confirm the action you are about to take. For example,
if you want to delete all addresses listed in the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Email
Status for &lt;Site Name&gt;</FONT></FONT></FONT> page, clicking on
the 
<FONT FACE="Verdana, sans-serif"><B>Delete Addresses</B></FONT>
button on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Email
Status for &lt;Site Name&gt;</FONT></FONT></FONT> page will take you
to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Confirm
Delete Email Addresses for &lt;Site Name&gt;</FONT></FONT></FONT>
page.</P>
<P CLASS="western">Clicking on the 
<FONT FACE="Verdana, sans-serif"><B>Help</B></FONT>
button on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Email
Status for &lt;Site Name&gt;</FONT></FONT></FONT> page opens the
<FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Email
Status Help</FONT></FONT></FONT> page in a new browser window.</P>

    
HERE;

    echo $msg;
    }


   /*
    |  Main program
    */
    
/*    $db = db_connect();
    db_change($GLOBALS['PREFIX'].'install',$db);
    $authuser = install_login($db);
    $comp = component_installed();
  
    $action = get_argument('action',0,'edit'); // non-admin user clicks on user navbar link 
    $title   = ucwords($action) . ' User Help';
    
    $user   = install_user($authuser,$db);    
    $admin  = @ ($user['priv_admin'])  ? 1 : 0;    
    $serv   = @ ($user['priv_servers'])  ? 1 : 0; 
    if ($id == 0) $id = $user['installuserid'];
*/    
    $msg = ob_get_contents();           // save the buffered output so we can...
    ob_end_clean();                     // (now dump the buffer) 
    echo html_header();
    if (trim($msg)) debug_note($msg);   // ...display any errors to debug users  

     
        
    newlines(1);   
    
    display_content();
    
    echo html_footer();
?>
