<?php

/* 
Revision history:

Date        Who     What
----        ---     ----
16-Sep-03   NL      Creation.
              
*/

    ob_start(); // avoid indavertantly sending output (before HTTP Headers sent) 

include_once ( 'htmlhead.php'        );
include_once ( 'htmlfoot.php'        );  

    function newlines($n)
    {
        for ($i = 0; $i < $n; $i++)
        {
            echo "<br>\n";
        }
    }

    function display_content()
    { 
    
        /*  The following HTML was generated by OpenOffice from the Word doc
            with the following changes:
            1.  Remove all references to below, shown below, seen below, and see below.
            2.  Remove all images; For form buttons, replace with text.
            3.  Nest lists as necessary.
            4.  Remove hyperlinks.
        */    
        
        $msg = <<< HERE

<H3 CLASS="western">Add e-mail addresses</H3>
<P CLASS="western">The <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
Email Addresses for &lt;Site Name&gt;</FONT></FONT></FONT> page
is the entry point for the email distribution
management module. 
<P CLASS="western">This page gives you two ways to enter e-mail
addresses, which can be used simultaneously:</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western">Enter e-mail addresses, one
	per line in the text box to the right of the label <FONT FACE="Verdana, sans-serif">Type
	new addresses</FONT>.</P>
	<LI><P CLASS="ww-list-bullet1-western">Copy and paste e-mail
	addresses from a text file where they are entered one per line</P>
	<LI><P CLASS="ww-list-bullet1-western"><A NAME="_1116929981"></A>Download
	e-mail addresses from a text file with one e-mail address per line.
	You can enter the full path for the file in the text box to the
	right of the label <FONT FACE="Verdana, sans-serif">Upload a file of
	addresses</FONT>, or select it by clicking on the 
	<FONT FACE="Verdana, sans-serif"><B>Browse</B></FONT>
	button. The contents of the file are added automatically to the text
	box to the right of the label <FONT FACE="Verdana, sans-serif">Type
	new addresses</FONT>.</P>
</UL>
<P CLASS="western">If you make mistakes in
entering the e-mail addresses, you can correct them manually, or you
can delete them by simply dragging your mouse across the one(s) you
want to delete. Once you have entered and reviewed the e-mail
addresses for accuracy and completeness, clicking on the 
<FONT FACE="Verdana, sans-serif"><B>Add Addresses</B></FONT>
button will take you to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Adding
Email Addresses for &lt;Site Name&gt;</FONT></FONT></FONT>  page.</P>
<P CLASS="western">Clicking on the 
<FONT FACE="Verdana, sans-serif"><B>Help</B></FONT>
button on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
Email Addresses for &lt;Site Name&gt;</FONT></FONT></FONT> page opens
the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
Email Addresses Help</FONT></FONT></FONT> page in a new browser
window.</P>
    
HERE;

    echo $msg;
    }


   /*
    |  Main program
    */
    
/*    $db = db_connect();
    db_change($GLOBALS['PREFIX'].'install',$db);
    $authuser = install_login($db);
    $comp = component_installed();
  
    $action = get_argument('action',0,'edit'); // non-admin user clicks on user navbar link 
    $title   = ucwords($action) . ' User Help';
    
    $user   = install_user($authuser,$db);    
    $admin  = @ ($user['priv_admin'])  ? 1 : 0;    
    $serv   = @ ($user['priv_servers'])  ? 1 : 0; 
    if ($id == 0) $id = $user['installuserid'];
*/    
    $msg = ob_get_contents();           // save the buffered output so we can...
    ob_end_clean();                     // (now dump the buffer) 
    echo html_header();
    if (trim($msg)) debug_note($msg);   // ...display any errors to debug users  

     
        
    newlines(1);   
    
    display_content();
    
    echo html_footer();
?>
