<?php

/* 
Revision history:

Date        Who     What
----        ---     ----
16-Sep-03   NL      Creation.
17-Sep-03   NL      Delete "(shown below)".
              
*/

    ob_start(); // avoid indavertantly sending output (before HTTP Headers sent) 

include_once ( 'htmlhead.php'        );
include_once ( 'htmlfoot.php'        );  

    function newlines($n)
    {
        for ($i = 0; $i < $n; $i++)
        {
            echo "<br>\n";
        }
    }

    function display_content()
    { 
    
        /*  The following HTML was generated by OpenOffice from the Word doc
            with the following changes:
            1.  Remove all references to below, shown below, seen below, and see below.
            2.  Remove all images; For form buttons, replace with text.
            3.  Nest lists as necessary.
            4.  Remove hyperlinks.
        */    
        
        $msg = <<< HERE

<H3 CLASS="western">Add ASI server</H3>
<P CLASS="western">Fields on this page are:</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif">Server
	Name </FONT>&ndash; the &ldquo;friendly&rdquo; name of the ASI
	server should be a single text string of up to 50 characters in
	length. When creating the &ldquo;friendly&rdquo; name of an ASI
	server you should avoid using the following characters:</P>
    <UL>
    	<LI><P CLASS="ww-list-bullet-21-western">&amp;</P>
    	<LI><P CLASS="ww-list-bullet-21-western">, (comma)</P>
    	<LI><P CLASS="ww-list-bullet-21-western">. (period)</P>
    </UL>
</UL>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif">User
	name</FONT> &ndash; this is the name of the user that will have
	access to the site&rsquo;s event, asset, and site management
	facilities on the ASI server. It should be a single text-only string
	of between x and y characters. As for <FONT FACE="Verdana, sans-serif">Server
	Name</FONT> you should not use &amp;, comma, or period. For ease of
	use, when creating a user name you might also want to avoid using
	upper case letters, or a mix of upper and lower case letters in user
	id&rsquo;s.</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif">Password</FONT><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT>&ndash; this should be a single text-only string of between x
	and y characters. For increased security, as you enter the password
	it is displayed as a string of <B><FONT SIZE=2 STYLE="font-size: 11pt">*</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif">Confirm
	Password</FONT><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash;
	to minimize the chance of making a data entry error, you are asked
	to re-enter the content entered in the Password field in this field.
	For increased security, as you enter the password it is displayed as
	a string of <B><FONT SIZE=2 STYLE="font-size: 11pt">*</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif">Notification
	email</FONT><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash; in
	this field, enter the e-mail address(es) of the recipient(s) of
	notifications sent via e-mail. Multiple addresses should be
	separated by commas. For example:
	<B><FONT FACE="Courier New, monospace">groucho@marxbrothers.com,chico@marxbrothers.com</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif">Report
	email</FONT><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash; in
	this field, enter the e-mail address(es) of the recipient(s) of
	reports produced for the site. Multiple addresses should be
	separated by commas. For example:
	<B><FONT FACE="Courier New, monospace">harpo@marxbrothers.com,zeppo@marxbrothers.com</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif">ASI
	Server URL</FONT> &ndash; Here you enter the URL for the ASI server.
	For example:, <B><FONT FACE="Courier New, monospace">https://hfn.service.com</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif">Available
	to all</FONT> &ndash; If selected, this option makes the ASI server
	whose information you are entering, or editing, available as a
	possible ASI server selection to all sites whose record is created,
	or accessible, by the currently logged in user.</P>
</UL>
<P CLASS="western">At the top and bottom of the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
ASI Server</FONT></FONT></FONT> page, you will find three buttons: 
</P>
<UL>
  	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Cancel &nbsp; Enter &nbsp; Help</B></FONT></P>
</UL>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Cancel</B></FONT>
takes you back to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">ASI
Servers</FONT></FONT></FONT> page without making any changes.</P>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Enter</B></FONT>
checks the site information for validity, and either takes you to the
<FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Creating ASI
Server </FONT></FONT></FONT>page, if no problem exists,
or to a page with the same name and a message explaining where the
error was made.</P>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Help</B></FONT>
opens the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
ASI Server Help</FONT></FONT></FONT> page in a new browser window.</P>
    
HERE;

    echo $msg;
    }


   /*
    |  Main program
    */
    
/*    $db = db_connect();
    db_change($GLOBALS['PREFIX'].'install',$db);
    $authuser = install_login($db);
    $comp = component_installed();
  
    $action = get_argument('action',0,'edit'); // non-admin user clicks on user navbar link 
    $title   = ucwords($action) . ' User Help';
    
    $user   = install_user($authuser,$db);    
    $admin  = @ ($user['priv_admin'])  ? 1 : 0;    
    $serv   = @ ($user['priv_servers'])  ? 1 : 0; 
    if ($id == 0) $id = $user['installuserid'];
*/    
    $msg = ob_get_contents();           // save the buffered output so we can...
    ob_end_clean();                     // (now dump the buffer) 
    echo html_header();
    if (trim($msg)) debug_note($msg);   // ...display any errors to debug users  

     
        
    newlines(1);   
    
    display_content();
    
    echo html_footer();
?>
