<?php

/* 
Revision history:

Date        Who     What
----        ---     ----
24-Jul-03   NL      Creation.
31-Jul-03   EWB     Uses install_login($db);
15-Sep-03   NL      Move from install/userhelp.php to install/help/useradd.php
                    Uses htmlhead, htmlfoot, updated content.
16-Sep-03   NL      Remove all images; remove hyperlinks; correct list formatting.
*/

    ob_start(); // avoid indavertantly sending output (before HTTP Headers sent) 

include_once ( 'htmlhead.php'        );
include_once ( 'htmlfoot.php'        );  

    function newlines($n)
    {
        for ($i = 0; $i < $n; $i++)
        {
            echo "<br>\n";
        }
    }

    function display_content()
    { 
    
        /*  The following HTML was generated by OpenOffice from the Word doc
            with the following changes:
            1.  Remove all references to (shown below), (seen below), and (see below).
            2.  Remove all images; For form buttons, replace with text.
            3.  Nest lists as necessary.
            4.  Remove hyperlinks.
        */    
        
        $msg = <<< HERE

<H3 CLASS="western">Edit site installation and deployment 
</H3>
<P CLASS="western">Clicking on the <FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">[edit]</FONT></U></FONT>
link in the <B><FONT FACE="Verdana, sans-serif">Action</FONT></B>
column in a site&rsquo;s installation and deployment entry on the
<FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Sites
</FONT></FONT></FONT>page takes you the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Edit
Site Installation and Deployment Information</FONT></FONT></FONT>
page where you can edit all of a site&rsquo;s record. 
</P>
<P CLASS="western">In fact, this page is an exact duplicate of the
<FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
Site Installation and Deployment</FONT></FONT></FONT> page, with all
the information filled in except for the site user password. The
current site name, and assigned registration code are displayed right
below the title of the page.</P>
<P CLASS="western">When you change a site&rsquo;s installation and
deployment information, the next time an ASI client is installed at
the site, and contacts the ASI installation management facility, it
will download the edited installation and deployment information, and
will update all other ASI clients at the site.</P>
<P CLASS="western" STYLE="page-break-inside: avoid">However, you may
also want to change a site&rsquo;s installation and deployment
information after deployment has already started. For example, you
may want to change the follow-on phase Scrip configuration, or you
may want to change the duration of the start-up phase or the action
at the end of the start-up phase.</P>
<P CLASS="western" STYLE="page-break-inside: avoid">In order to
change the deployment of the ASI client at a site after the start-up
phase is already under way, you would change the configuration of the
ASI client installation and deployment Scrip either by directly
logging onto the ASI client Scrip configurator on any system at the
site using any browser, or logging onto the ASI server configuration
module.</P>
<P CLASS="western" STYLE="page-break-inside: avoid">Please refer to
the &ldquo;Automated Support Infrastructure Site Management User
Guide&rdquo; for detailed instructions on how to make such a Scrip
configuration change.</P>
<P CLASS="western" STYLE="page-break-inside: avoid">The site
installation and deployment information that cannot be changed as
described above is:</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Site
	name</B></FONT></P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Site
	email domain</FONT></B> 
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Site
	user name</FONT></B> 
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Site
	password</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Confirm
	password</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">ASI
	server</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Proxy
	URL</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Logging
	email address</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Bounce
	email</B> </FONT>
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Download
	URL</B> </FONT>
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Email
	distribution message</B> </FONT>
	</P>
</UL>
<P CLASS="western">The above site installation and deployment
information can be changed only by accessing the ASI installation
management facility. However, it should be noted that none of the
above information affects either the start-up or follow-on deployment
phases.</P>
<P CLASS="western">At the top and bottom of the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Edit
Site Installation and Deployment Information</FONT></FONT></FONT>
page, you will find four buttons: 
</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western">
	<FONT FACE="Verdana, sans-serif"><B>Cancel &nbsp; Help &nbsp; Reset to Default Values &nbsp; Update</B></FONT>
	</P>
</UL>
<P CLASS="western">Clicking on <FONT FACE="Verdana, sans-serif"><B>Cancel</B></FONT>
takes you back to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Sites</FONT></FONT></FONT>
page without making any changes.</P>
<P CLASS="western">Clicking on <FONT FACE="Verdana, sans-serif"><B>Help</B></FONT>
opens the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Edit
Site Help</FONT></FONT></FONT> page in a new browser window.</P>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Reset to Default Values</B></FONT>
resets the values of all site installation and deployment information
entries to their default values as defined in the profile of the user
currently logged in.</P>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Update</B></FONT>
checks the site information for validity, and either takes you to the
<FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Updating
Site </FONT></FONT></FONT>page, if the site update
operation was completed successfully, or to a page with the same name
and a message explaining where the error was made.</P>

HERE;

    echo $msg;
    }


   /*
    |  Main program
    */
    
/*    $db = db_connect();
    db_change($GLOBALS['PREFIX'].'install',$db);
    $authuser = install_login($db);
    $comp = component_installed();
  
    $action = get_argument('action',0,'edit'); // non-admin user clicks on user navbar link 
    $title   = ucwords($action) . ' User Help';
    
    $user   = install_user($authuser,$db);    
    $admin  = @ ($user['priv_admin'])  ? 1 : 0;    
    $serv   = @ ($user['priv_servers'])  ? 1 : 0; 
    if ($id == 0) $id = $user['installuserid'];
*/    
    $msg = ob_get_contents();           // save the buffered output so we can...
    ob_end_clean();                     // (now dump the buffer) 
    echo html_header();
    if (trim($msg)) debug_note($msg);   // ...display any errors to debug users  

     
        
    newlines(1);   
    
    display_content();
    
    echo html_footer();
?>
