<?php

/* 
Revision history:

Date        Who     What
----        ---     ----
24-Jul-03   NL      Creation.
31-Jul-03   EWB     Uses install_login($db);
15-Sep-03   NL      Move from install/userhelp.php to install/help/useradd.php
                    Uses htmlhead, htmlfoot, updated content.
16-Sep-03   NL      Remove all images; remove hyperlinks; correct list formatting.
*/

    ob_start(); // avoid indavertantly sending output (before HTTP Headers sent) 
 
include_once ( 'htmlhead.php'        );
include_once ( 'htmlfoot.php'        );  

    function newlines($n)
    {
        for ($i = 0; $i < $n; $i++)
        {
            echo "<br>\n";
        }
    }

    function display_content()
    { 
    
        /*  The following HTML was generated by OpenOffice from the Word doc
            with the following changes:
            1.  Remove all references to (shown below), (seen below), and (see below).
            2.  Remove all images; For form buttons, replace with text.
            3.  Nest lists as necessary.
            4.  Remove hyperlinks.
        */    
        
        $msg = <<< HERE

<H3 CLASS="western">Edit user</H3>
<P CLASS="western">Clicking on the <FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">[edit]</FONT></U></FONT><FONT FACE="Verdana, sans-serif">
</FONT>link in the <B><FONT FACE="Verdana, sans-serif">Action</FONT></B>
column in a user entry on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Users
</FONT></FONT></FONT>page will take you to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Edit
User</FONT></FONT></FONT> page where you can edit all
of a user&rsquo;s profile information.</P>

<P CLASS="western">Please note that changing a user&rsquo;s default
information will not change the installation and deployment
information of sites whose installation and deployment profile was
set up using a user&rsquo;s default values.</P>
<P CLASS="western">When you create the send mail record of a site (by
clicking on the <FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">send
email</FONT></U></FONT><FONT FACE="Verdana, sans-serif"><FONT SIZE=1 STYLE="font-size: 7pt">
</FONT></FONT>link in the second-level navigation bar labeled <FONT FACE="Verdana, sans-serif"><FONT SIZE=1 STYLE="font-size: 7pt"><B><FONT SIZE=2>manage
email distribution)</FONT></B></FONT></FONT>, the fields described
below that are also in a the send mail record of a site will be
filled in automatically with the default values entered in the record
of the user logged in at the time the site record is being created.
For each send mail record, you can change the default values when you
create the send mail record, or when you edit it at a later time.</P>
<P CLASS="western">The fields on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Edit
User</FONT></FONT></FONT> page are:</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">User
	name</FONT></B> &ndash; this should be a single text-only string of
	between x and y characters When creating a user name you should
	avoid using the following characters:</P>
    <UL>
    	<LI><P CLASS="ww-list-bullet-21-western">&amp;</P>
    	<LI><P CLASS="ww-list-bullet-21-western">, (comma)</P>
    	<LI><P CLASS="ww-list-bullet-21-western">. (period)</P>
    </UL>
</UL>
<P CLASS="western">For ease of use, when creating a user name you
might also want to avoid using upper case letters, or a mix of upper
and lower case letters in user id&rsquo;s.</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Password</FONT><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B>&ndash; this should be a single text-only string of
	between x and y characters. For increased security, as you enter the
	password it is displayed as a string of <B><FONT SIZE=2 STYLE="font-size: 11pt">*</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Confirm
	Password</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash;
	to minimize the chance of making a data entry error, you are asked
	to re-enter the content entered in the Password field in this field.
	For increased security, as you enter the password it is displayed as
	a string of <B><FONT SIZE=2 STYLE="font-size: 11pt">*</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Administrator?</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT>&ndash; this check box is available only if the logged in
	user has administrative privileges. Only a user with administrative
	privileges can add users, give them administrative privileges, and
	give them access to the ASI server and Email Distribution Modules. 
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">ASI
	server?</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash;
	this check box is available only if the logged in user has
	administrative privileges because only a user with administrative
	privileges can give users access to the ASI server module.</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Email
	distribution?</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash;
	this check box is available only if the logged in user has
	administrative privileges because only a user with administrative
	privileges can give users access to the Email Distribution module.</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Site
	user name</FONT></B> <B><FONT FACE="Verdana, sans-serif">(default)</FONT><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B>&ndash; Logged in as this user, you will be able to
	directly access the ASI client on any system at a site via the
	client browser based interface. This <FONT FACE="Verdana, sans-serif">User
	name</FONT> should be a single text-only string of between x and y
	characters. As for <FONT FACE="Verdana, sans-serif">Server Name</FONT>
	you should not use &amp;, comma, or period. For ease of use, when
	creating a user name you might also want to avoid using upper case
	letters, or a mix of upper and lower case letters in user id&rsquo;s.</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Site
	password</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT><B><FONT FACE="Verdana, sans-serif">(default)</FONT><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B>&ndash; this should be a single text-only string of
	between x and y characters. For increased security, as you enter the
	password it is displayed as a string of <B><FONT SIZE=2 STYLE="font-size: 11pt">*</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Confirm
	password</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash;
	to minimize the chance of making a data entry error, you are asked
	to re-enter the content entered in the Password field in this field.
	For increased security, as you enter the password it is displayed as
	a string of <B><FONT SIZE=2 STYLE="font-size: 11pt">*</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Logging
	email address</FONT></B> <B><FONT FACE="Verdana, sans-serif">(default)</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT>&ndash; this is the email address that is used by the ASI
	clients at your sites when they need to directly send email to the
	ASI server. This is currently only used when email logging is
	enabled on the ASI client. By default it is not.</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">ASI
	server</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT><B><FONT FACE="Verdana, sans-serif">(default)</FONT><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B>&ndash; From this pull-down list you select the default
	ASI server used by ASI clients at your sites. Clicking on the <FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">[edit
	servers]</FONT></U></FONT> link to the right of the entry takes
	you to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">ASI
	Servers</FONT></FONT></FONT> page where you can edit the information
	for an existing ASI server or add information for another one.</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Proxy
	URL</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT><B><FONT FACE="Verdana, sans-serif">(default)</FONT><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B>&ndash; If no proxy server is used at the site, leave
	this entry blank. If a proxy server is used at the site, please
	enter the site-specific address of the proxy server and the port it
	uses. If the proxy server at the site requires authentication, you
	should add a working user id and password to the proxy URL. The
	syntax of an entry in <B><FONT FACE="Verdana, sans-serif">Proxy URL</FONT></B>
	is:</P>
    <UL>
    	<LI><P CLASS="ww-list-bullet-21-western">http://&lt;user name&gt;:&lt;user
    	password&gt;@&lt;proxy server name&gt;:&lt;proxy port&gt; 
    	</P>
    </UL>
    <P CLASS="western">Please remember that ASI requires
    that ports 80, 443, and 37 (time server) be left open for outbound
    communication.</P>
</UL>

<UL>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Start-up
	Scrip configuration</B> <B>(default)</B></FONT><B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B><FONT FACE="Verdana, sans-serif">&ndash; </FONT>From this
	pull-down list you select the default Scrip configuration for the
	ASI client at your sites, after installation is completed. The list
	includes all Scrip configurations defined for the user currently
	logged in, plus the two special options &quot;All&quot; and &quot;None&quot;.
	The &ldquo;All&rdquo; configuration option enables all Scrips. The
	&ldquo;None&rdquo; configuration option puts the ASI client in
	dormant state for an indefinite period of time. In this state, a
	minimum number of Scrips are enabled are sufficient to let you
	activate the ASI client at a time of your choosing. Clicking on the 
    <FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">[edit
	Scrip configurations]</FONT></U></FONT> link to the right of the
	<FONT FACE="Verdana, sans-serif">Scrip Configurations</FONT> entry
	takes you to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Scrip
	Configurations</FONT></FONT></FONT> page where you can edit the
	information for an existing list or add another one.</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Follow-on
	Scrip configuration</B> <B>(default)</B></FONT><B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B><FONT FACE="Verdana, sans-serif">&ndash; </FONT>From this
	pull-down list you select the default Scrip configuration that the
	ASI clients at your sites will use after the start-up phase is over.
	The list includes all follow-on options defined for the user
	currently logged in, plus the three special options &quot;All&quot;,
	&quot;None&quot;, and &ldquo;Uninstall. The &ldquo;All&rdquo;
	configuration option enables all Scrips. The &ldquo;None&rdquo;
	configuration option puts the ASI client in dormant state for an
	indefinite period of time. In this state, a minimum number of Scrips
	are enabled are sufficient to let you activate the ASI client at a
	time of your choosing. Selecting &ldquo;Uninstall&rdquo;, will
	result in removal of the ASI client from all systems where it was
	installed for the start-up phase. Clicking on the 
    <FONT COLOR="#0000ff"><U><FONT FACE="Verdana, sans-serif">[edit
	Scrip configurations]</FONT></U></FONT> link to the right of the
	<FONT FACE="Verdana, sans-serif">Follow-on Scrip configuration</FONT>
	entry takes you to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Scrip
	Configurations</FONT></FONT></FONT> page where you can edit the
	information for an existing list or add another one.</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Delay
	before follow-on</B> <B>(default)</B></FONT><B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B><FONT FACE="Verdana, sans-serif">&ndash; </FONT>in these
	fields you enter the default amount of time you want the ASI client
	to operate in start-up mode before moving to the follow-on phase,
	and applying the follow-on phase actions selected from the <FONT FACE="Verdana, sans-serif">Follow-on
	Scrips configuration</FONT> pull-down list. Please note that the
	<B><FONT FACE="Verdana, sans-serif">Delay before follow-on</FONT></B>
	fields have a default value of <B><FONT FACE="Courier New, monospace">0</FONT></B>.
	Leaving the default value unchanged effectively means that the
	start-up and follow-on phases are one and the same.</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Sender
	(default)</FONT></B> &ndash; This is the e-mail address that will be
	displayed as the sending and reply-to address in the ASI client
	distribution and installation e-mail message. 
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Extra
	headers (default)</B> </FONT>&ndash; In addition to the e-mail
	address the ASI client distribution and installation e-mail message
	is being sent to, the sending e-mail address, and the subject line,
	you can add other headers in this field, each on a different line.
	Following are some common headers and their format:</P>
    <UL>
    	<LI><P CLASS="ww-list-bullet-21-western">X-Priority: (integer
    	between 1, highest and 5)</P>
    	<LI><P CLASS="ww-list-bullet-21-western">Cc: &lt;e-mail address&gt;
    	(if more than one address is entered, addresses should be separated
    	by a comma with no spaces)</P>
    	<LI><P CLASS="ww-list-bullet-21-western">Bcc: &lt;e-mail address&gt;
    	(if more than one address is entered, addresses should be separated
    	by a comma with no spaces)</P>
    </UL>
</UL>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Subject
	(default)</FONT></B> &ndash; Here you enter the subject of the ASI
	client distribution and installation e-mail message.</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Email
	distribution message</B> <B>(default)</B></FONT><B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B><FONT FACE="Verdana, sans-serif">&ndash; </FONT>In this
	field you can enter content for the default ASI client installation
	e-mail message sent by the email distribution management module.</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Download
	URL</B> <B>(default)</B></FONT><B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B><FONT FACE="Verdana, sans-serif">&ndash; </FONT>In this
	field, you have the option enter the default URL for downloading the
	ASI client installation executable. 
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Bounce
	email</B> <B>(default)</B></FONT><B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B><FONT FACE="Verdana, sans-serif">&ndash; </FONT>In this
	field, you have the option to enter a site specific e-mail address
	to be used by the email distribution management module as the return
	destination for the ASI client installation e-mail messages that did
	not reach their original destination.</P>
</UL>
<P CLASS="western">At the top and bottom of the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Edit
User</FONT></FONT></FONT> page, you will find three buttons: 
</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Cancel &nbsp; Help &nbsp; Update</B></FONT></P>
</UL>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Cancel</B></FONT>
takes you back to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Users</FONT></FONT></FONT>
page without making any changes.</P>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Help</B></FONT>
opens the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Edit
User Help</FONT></FONT></FONT> page in a new browser window.</P>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Update</B></FONT>
checks the user information for validity, and either takes you to the
<FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Updating
User </FONT></FONT></FONT>page, if the user update
operation was completed successfully, or to a page with the same name
and a message explaining where the error was made.</P>
    
HERE;

    echo $msg;
    }


   /*
    |  Main program
    */
    
/*    $db = db_connect();
    db_change($GLOBALS['PREFIX'].'install',$db);
    $authuser = install_login($db);
    $comp = component_installed();
  
    $action = get_argument('action',0,'edit'); // non-admin user clicks on user navbar link 
    $title   = ucwords($action) . ' User Help';
    
    $user   = install_user($authuser,$db);    
    $admin  = @ ($user['priv_admin'])  ? 1 : 0;    
    $serv   = @ ($user['priv_servers'])  ? 1 : 0; 
    if ($id == 0) $id = $user['installuserid'];
*/    
    $msg = ob_get_contents();           // save the buffered output so we can...
    ob_end_clean();                     // (now dump the buffer) 
    echo html_header();
    if (trim($msg)) debug_note($msg);   // ...display any errors to debug users  

     
        
    newlines(1);   
    
    display_content();
    
    echo html_footer();
?>
