<?php

/* 
Revision history:

Date        Who     What
----        ---     ----
24-Jul-03   NL      Creation.
31-Jul-03   EWB     Uses install_login($db);
15-Sep-03   NL      Move from install/userhelp.php to install/help/useradd.php
                    Uses htmlhead, htmlfoot, updated content.
16-Sep-03   NL      Remove all images; remove hyperlinks; correct list formatting.                    
*/

    ob_start(); // avoid indavertantly sending output (before HTTP Headers sent) 

include_once ( 'htmlhead.php'        );
include_once ( 'htmlfoot.php'        );  

    function newlines($n)
    {
        for ($i = 0; $i < $n; $i++)
        {
            echo "<br>\n";
        }
    }

    function display_content()
    { 
    
        /*  The following HTML was generated by OpenOffice from the Word doc
            with the following changes:
            1.  Remove all references to (shown below), (seen below), and (see below).
            2.  Remove all images; For form buttons, replace with text.
            3.  Nest lists as necessary.
            4.  Remove hyperlinks.
        */    
        
        $msg = <<< HERE

<H3 CLASS="western">Add User 
</H3>
<P CLASS="western">The <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
User</FONT></FONT></FONT> page lets you add users that
will have access to the ASI Installation management facility. You are
able to give users privileges to match the tasks you want them to be
able to perform. 
</P>
<P CLASS="western">To increase the efficiency of the ASI client
installation and deployment management process, the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
User</FONT></FONT></FONT> page lets you enter default values for
information necessary for installation and deployment of the ASI
client at all sites. When you add the installation and deployment
information for a site on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
Site Installation and Deployment Information</FONT></FONT></FONT>
page, the default values you enter as part of the user profile on the
<FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
User</FONT></FONT></FONT> page, are used to automatically fill in the
corresponding fields in the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
Site Installation and Deployment Information</FONT></FONT></FONT>
page.</P>
<P CLASS="western">Fields on the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
User</FONT></FONT></FONT> page are:</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">User
	name</FONT></B> &ndash; this should be a single text-only string of
	between x and y characters When creating a user name you should
	avoid using the following characters:</P>
    <UL>
    	<LI><P CLASS="ww-list-bullet-21-western">&amp;</P>
    	<LI><P CLASS="ww-list-bullet-21-western">, (comma)</P>
    	<LI><P CLASS="ww-list-bullet-21-western">. (period)</P>
    </UL>
</UL>
<P CLASS="western">For ease of use, when creating a user name you
might also want to avoid using upper case letters, or a mix of upper
and lower case letters in user id&rsquo;s.</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Password</FONT><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT></B>&ndash; this should be a single text-only string of
	between x and y characters. For increased security, as you enter the
	password it is displayed as a string of <B><FONT SIZE=2 STYLE="font-size: 11pt">*</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Confirm
	Password</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash;
	to minimize the chance of making a data entry error, you are asked
	to re-enter the content entered in the Password field in this field.
	For increased security, as you enter the password it is displayed as
	a string of <B><FONT SIZE=2 STYLE="font-size: 11pt">*</FONT></B></P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Administrator?</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt">
	</FONT>&ndash; this check box is available only if the logged in
	user has administrative privileges. Only a user with administrative
	privileges can add users, give them administrative privileges, and
	give them access to the ASI server and Email Distribution Modules. 
	</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">ASI
	server?</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash;
	this check box is available only if the logged in user has
	administrative privileges because only a user with administrative
	privileges can give users access to the ASI server module.</P>
	<LI><P CLASS="ww-list-bullet1-western"><B><FONT FACE="Verdana, sans-serif">Email
	distribution?</FONT></B><FONT SIZE=1 STYLE="font-size: 7pt"> </FONT>&ndash;
	this check box is available only if the logged in user has
	administrative privileges because only a user with administrative
	privileges can give users access to the Email Distribution module.</P>
</UL>
<P CLASS="western">At the top and bottom of the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
User</FONT></FONT></FONT> page, you will find three buttons: 
</P>
<UL>
	<LI><P CLASS="ww-list-bullet1-western"><FONT FACE="Verdana, sans-serif"><B>Cancel &nbsp; Help &nbsp; Enter</B></FONT></P>
</UL>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Cancel</B></FONT>
takes you back to the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Users</FONT></FONT></FONT>
page without making any changes.</P>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Help</B></FONT>
opens the <FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Add
User Help</FONT></FONT></FONT> page in a new browser window.</P>
<P CLASS="western">Clicking on 
<FONT FACE="Verdana, sans-serif"><B>Enter</B></FONT>
checks the user information for validity, and either takes you to the
<FONT SIZE=2 STYLE="font-size: 11pt"><FONT FACE="Verdana, sans-serif"><FONT COLOR="#333399">Adding
User </FONT></FONT></FONT>page, if the user creation
operation was completed successfully, or to a page with the same name
and a message explaining where the error was made.</P>
<P CLASS="western"><BR><BR>
</P>
              


    
HERE;

    echo $msg;
    }


   /*
    |  Main program
    */
    
/*    $db = db_connect();
    db_change($GLOBALS['PREFIX'].'install',$db);
    $authuser = install_login($db);
    $comp = component_installed();
  
    $action = get_argument('action',0,'edit'); // non-admin user clicks on user navbar link 
    $title   = ucwords($action) . ' User Help';
    
    $user   = install_user($authuser,$db);    
    $admin  = @ ($user['priv_admin'])  ? 1 : 0;    
    $serv   = @ ($user['priv_servers'])  ? 1 : 0; 
    if ($id == 0) $id = $user['installuserid'];
*/    
    $msg = ob_get_contents();           // save the buffered output so we can...
    ob_end_clean();                     // (now dump the buffer) 
    echo html_header();
    if (trim($msg)) debug_note($msg);   // ...display any errors to debug users  

     
        
    newlines(1);   
    
    display_content();
    
    echo html_footer();
?>
